apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
  #namespace: first-app
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS usermgmt;
    CREATE DATABASE usermgmt;
